### ISSUE TITLE
Feature: User can click to play or see the rules

### ISSUE THREAD

**Issue by heesoo-kim97** [heesoo-kim97/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click to play or click to see the rules

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can see two buttons in the home page that the user can click to see set of rules or click play to move onto the game

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-07-27 at 1 18 47 PM](https://user-images.githubusercontent.com/82424354/127221777-0cf1f43e-4312-4014-9078-6d26e0aee8a5.png)

![Screen Shot 2021-07-27 at 1 18 40 PM](https://user-images.githubusercontent.com/82424354/127221752-e57e3f60-9d3a-4f71-bb51-30817a7feec3.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... 
- [x] make container for Home page
- [x] Set background image to casino grassy table
- [x] Display blackjack with Ace card image and 10 card image
- [x] Display the title "Blackjack"
- [x] Display star with Play button and star with rules button
- [x] Make a rules container that displays all the rules once rules button is clicked
- [x] Make return button that allows user to return to Home Page from Rules page
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
