### ISSUE TITLE
Feature: User can select betting amount and see bank information

### ISSUE THREAD

**Issue by heesoo-kim97** [heesoo-kim97/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can select betting amount and number of money to start with in the bank.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When user clicks play on Home page a modal will ask to choose betting amount and can see bank amount. Since the user hasn't started the game yet , the total bank amount will be $100.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-07-28 at 4 50 14 PM](https://user-images.githubusercontent.com/82424354/127410732-227c921e-7004-4b5d-a9b1-db96f161555c.png)
![Screen Shot 2021-07-28 at 4 50 40 PM](https://user-images.githubusercontent.com/82424354/127410739-8f51e1b5-1d0e-40bc-bcc3-31b570db7950.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... 
- [x] Create a bet modal container
- [x] Add form to the modal
- [x] Add heading for "choose your bet!"
- [x] insert select with options of possible bets
- [x] Insert text and numbers for number of decks and bank amount
- [x] Insert game-play button that moves onto blackjack table for game
- [x] Make the Home-play button to move to bet modal
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
