### ISSUE TITLE
Feature: User can click start and view the cards drawn

### ISSUE THREAD

**Issue by heesoo-kim97** [heesoo-kim97/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

This feature allows the user to click start on betting modal and view the cards drawn for the game to start.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can click the start button at the bottom of the bet modal which will lead to game table with cards laid out for the player and the dealer.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![Screen Shot 2021-07-29 at 1 14 50 PM](https://user-images.githubusercontent.com/82424354/127559674-ddaa5a3d-ac01-4448-8290-cbafba1bcfd1.png)
![Screen Shot 2021-07-29 at 1 15 00 PM](https://user-images.githubusercontent.com/82424354/127559676-a1d83965-b1d0-4685-81c4-8c5e66d3be22.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] create game table container
- [x] Add the term Dealer and Player on the game table container with styling
- [x] change play button to start button
- [x] Make sure that clicking start button allows the user to move to the game table container
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] create data model
          - [ ] that has properties for what the total value is for the player
          - [ ] what card id is received for players
          - [ ] what total value is for the dealer
          - [ ] what card id is received for dealer
          - [ ] Remaining cards in the deck
- [x] Define function getCardDeckData in main.js
- [ ] Draw data from Deck of Cards API obtaining image, deck-id, card-id, and remaining card number
- [ ] Display two card image for the player from random draw
- [ ] Display one card image for the dealer from random draw
- [ ] Display one face down card image for the dealer
- [ ] Display number of the total value of the current cards
- [x] Use GET to retrieve data from Deck of Cards API.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
